# Generated by Django 5.2.10 on 2026-01-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('answers', models.JSONField()),
                ('recommended_products', models.JSONField()),
                ('product_links', models.JSONField(blank=True, default=list)),
                ('segment', models.CharField(blank=True, max_length=32)),
                ('customer_type', models.CharField(blank=True, max_length=32)),
                ('goal', models.CharField(blank=True, max_length=64)),
            ],
        ),
    ]
